# apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix-deployment
spec:
  selector:
    matchLabels:
      app: ngnix
    replicas: 2
    template:
      metadata:
        labels:
          app: nginx
        spec:
          containers:
            - name: nginx
              image: ngnix:1.14.2
              ports:
                - containerPort: 80